export interface IOrder {
    orderId: string;
    registrationId: string;
    emailId: number;
    deliveryAddressId: number;
    phoneNumber: string;
    customerComments: string;
    orderTotal: number;
    orderPlaced: Date;
    finished: boolean;
    returned: boolean;
    cancelled: boolean;
    pickedUp: boolean;
    refunded: boolean;
    paymentReceived: boolean;
    pickUpTime: Date;
    payout: Date | null;
    preparationTime: number;
    managementComments: string;
    orderHistory: string;
    bookingId: string;
    status: string;
    mercadoPagoMail: string;
    mercadoPagoName: string;
    mercadoPagoUsername: string;
    mercadoPagoTransaction: string;
    friendlyBookingId: string;
    statusSpanish: string;
    customerName: string;
    customerNumbers: string;
    discountId: number;
    pickUpTimeFrom: Date | null;
    totalInStore: number;
    payerIdType: string;
    payerIdNumber: string;
    cardHolderName: string;
    cardHolderType: string;
    cardHolderNumber: string;
    cuit: string;
}
